---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alspin.
--- DateTime: 20/01/2024 10:36
---

package("orion")
    set_description("The orion package")
    set_homepage("https://github.com/alspin8/Orion")
    set_license("MIT")

    add_urls("https://github.com/alspin8/Orion.git")

    add_versions("1.0a1", "d12a059733773f90e1e6148b13fe26e34dedadaf")

    on_install(function (package)
        import("package.tools.xmake").install(package)
    end)

    --on_test(function (package)
    --    assert(package:check_cxxsnippets({test = [[
    --        void test(int args, char** argv) {
    --            orion::Vector3f v;
    --        }
    --    ]]}, { includes = { "orion/omath.h" } }))
    --end)