---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alspin.
--- DateTime: 20/01/2024 10:36
---

package("orion")
    set_description("The orion package")
    set_homepage("https://github.com/devalexx/Orion")
    set_license("MIT")

    set_urls("https://github.com/devalexxx/Orion.git")

    add_versions("1.0a1", "7e97f7aa8ab3a9131657e1203c7937ccea19448b")

    add_deps("glfw", "glew", "fmt", "stb")

    on_install(function (package)
        local configs = {}
        configs.unittest = false
        configs.sandbox  = false
        configs.examples = false
        configs.nogpu    = false

        configs.mode   = package:is_debug() and "debug" or "release"
        configs.shared = package:config("shared")

        import("package.tools.xmake").install(package, configs)
    end)

    on_test(function (package)
        assert(package:check_cxxsnippets({test = [[
            void test(int args, char** argv) {
                orion::Vector3f v;
            }
        ]]}, { configs = {languages = "c++23"}, includes = { "orion/omath.h" } }))
    end)