---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by devalexx.
--- DateTime: 10/02/2024 23:26
---

package("hexis")
    set_description("The hexis package")
    set_homepage("https://github.com/devalexxx/Hexis")
    set_license("MIT")

    set_urls("https://github.com/devalexxx/Hexis.git")

    add_configs("shared", { description = "Build shared library.", default = false, type = "boolean" })
    add_configs("math",   { description = "Use the math module",   default = false, type = "boolean" })

    on_component("core", function(package, component)
        -- component:add("links", "HXCore")
    end)

    on_component("math", function(package, component)
        -- component:add("links", "HXMath")
        component:add("deps", "core")
    end)

    on_load(function (package)
        package:add("components", "core")

        -- Adding selected components
        for _, component in ipairs({ "math" }) do
            if package:config(component) then
                package:add("components", component)
            end
        end
    end)

    on_install(function (package)
        local configs = {}
        configs.unittest = false

        configs.mode   = package:is_debug() and "debug" or "release"
        configs.shared = package:config("shared")

        -- Adding selected component
        for _, component in ipairs({ "math" }) do
            if package:config(component) then
                configs[component] = true
            end
        end

        import("package.tools.xmake").install(package, configs)
    end)

    on_test(function (package)
        assert(package:check_cxxsnippets({test = [[
            void test(int args, char** argv) {
                Hx::TypeList<int, float>;
            }
        ]]}, { configs = { languages = "c++23" }, includes = { "Hexis/Core/TypeList.h" } }))

        if package:config("math") then
            assert(package:check_cxxsnippets({test = [[
                void test(int args, char** argv) {
                    Hx::Equal(1.f, 1.f);
                }
            ]]}, { configs = { languages = "c++23" }, includes = { "Hexis/Math/FloatingPoint.h" } }))
        end
    end)