---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by devalexx.
--- DateTime: 10/02/2024 23:26
---

package("hexis")
    set_description("The hexis package")
    set_homepage("https://github.com/devalexxx/Hexis")
    set_license("MIT")

    set_urls("https://github.com/devalexxx/Hexis.git")

    add_versions("latest", "037dc206b4052624427941c77b9a80c3bc225ef2")

    on_components("Math", function(package, component)
        component::add("deps", "Core")
    end)

    on_load(function (package)
        package::add("components", "Core")
        package::add("components", "Math")
    end)

    on_install(function (package)
        local configs = {}
        configs.unittest = false

        configs.mode   = package:is_debug() and "debug" or "release"
        configs.shared = package:config("shared")

        import("package.tools.xmake").install(package, configs)
    end)

    on_test(function (package)
        assert(package:check_cxxsnippets({test = [[
            void test(int args, char** argv) {
                Hexis::Vec3f v;
            }
        ]]}, { configs = {languages = "c++23"}, includes = { "Hexis/Math/Vec3.h" } }))
    end)