---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by devalexx.
--- DateTime: 10/02/2024 23:26
---

package("hexis")
    set_description("The hexis package")
    set_homepage("https://github.com/devalexxx/Hexis")
    set_license("MIT")

    set_urls("https://github.com/devalexxx/Hexis.git")

    on_component("Core", function(package, component)
        -- component:add("links", "libMath")
    end)

    on_component("Math", function(package, component)
        -- component:add("links", "libMath")
        component:add("deps", "Core")
    end)

    on_load(function (package)
        package:add("components", "Core")
        package:add("components", "Math")
    end)

    on_install(function (package)
        local configs = {}
        configs.unittest = false

        configs.mode   = package:is_debug() and "debug" or "release"
        configs.shared = package:config("shared")

        import("package.tools.xmake").install(package, configs)
    end)

    on_test(function (package)
        assert(package:check_cxxsnippets({test = [[
            void test(int args, char** argv) {
                Hx::Vec3f v(1.F, 2.F, 3.F);
            }
        ]]}, { configs = {languages = "c++23"}, includes = { "Hexis/Math/Vec3.h" } }))
    end)